### ISSUE TITLE
Can you release to quicklisp?

### ISSUE THREAD

**Issue by psilord** [markcox80/specialization-store#2] opened 2018-12-10 08:54 UTC
I believe that there are some recent commits that need to be tagged as releasable for quicklisp. Might I humbly request that this happen? Thank you!

**Comment by markcox80** [comment] 2018-12-11 00:44
Sorry about the delay.

I have [started](https://github.com/quicklisp/quicklisp-projects/issues/1604) the process to update quicklisp.

**Comment by mfiano** [comment] 2019-02-03 17:04
You forgot to make a release and it missed 2 QL dists :)

**Comment by markcox80** [comment] 2019-02-03 23:20
I'm not sure I follow. As far as I know, v0.0.4 of specialization-store made the [2019-01 quicklisp dist update](https://blog.quicklisp.org/2019/01/january-2019-quicklisp-dist-update-now.html). I just performed `(quicklisp:quickload "specialization-store")` and it fetched v0.0.4. 
```
cl-user> (quicklisp:quickload "specialization-store")
To load "specialization-store":
  Load 3 ASDF systems:
    alexandria asdf introspect-environment
  Install 1 Quicklisp release:
    specialization-store
; Fetching #<url "http://beta.quicklisp.org/archive/specialization-store/2019-01-07/specialization-store-v0.0.4.tgz">
; 62.83KB
==================================================
64,336 bytes in 0.03 seconds (2326.97KB/sec)
; Loading "specialization-store"
[package specialization-store.features]...........
[package specialization-store]....................
[package specialization-store.lambda-lists].......
[package specialization-store.dispatch]...........
[package specialization-store.dispatch.fixed-arity]
[package specialization-store.dispatch.variable-arity]
[package specialization-store.standard-store].....
[package specialization-store.globals]............
[package specialization-store.mop]................
............
("specialization-store")
cl-user> 
```

I'm currently waiting for the issue to be closed in [quicklisp-projects](https://github.com/quicklisp/quicklisp-projects/issues/1604).

**Comment by mfiano** [comment] 2019-02-03 23:25
Ok ignore me. I see it really has been that long (July) since I was waiting and it did infact land in QL. Sorry. It seems I missed the january update and did an update from dec->feb and didn't see it in the update log.

**Comment by markcox80** [comment] 2019-03-07 19:50
Specialization-store has been updated and the issue is now closed in [quicklisp-projects](https://github.com/quicklisp/quicklisp-projects/issues/1604).

**Closed as completed by markcox80** 2019-03-07 19:50 UTC
